Vagrant.configure("2") do |config|
 
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "ubuntu/focal64"
    ubuntu1.vm.network "private_network", ip: "192.168.56.100"
    ubuntu1.vm.provider "virtualbox" do |vb| 
        vb.memory = 1024
        vb.cpus = 1
    end
    ubuntu1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install net-tools -y
    SHELL
  end
 
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "ubuntu/focal64"
    ubuntu2.vm.network "private_network", ip: "192.168.56.101"
    ubuntu2.vm.provider "virtualbox" do |vb| 
        vb.memory = 1024
        vb.cpus = 1
    end
    ubuntu2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install net-tools -y
    SHELL
  end
end
