apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: deployment-nginx
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx-pods
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-pods
    spec:
      containers:
        - image: nginx
          name: nginx-container
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
            requests:
              cpu: "0.25"
              memory: 128Mi